### ISSUE TITLE
Steam Proton integration?

### ISSUE THREAD

**Issue by shpinog** [0e4ef622/wine-discord-ipc-bridge#3]
Is it possible to do something like a GameMode (library), which could be specified in the launch parameters of the steam game, like wdib% command%?

UPD: ok, im find script
Or ask to join  function does not apply to this ?

**Comment by 0e4ef622** [comment]
I'm not sure what it is you're asking.

**Comment by thibaultmol** [comment]
I think what he's asking is a way to just launch the script when you start up a specific game (by putting a launch command in the launch options of a game. but I don't know if that works) 
![Screenshot_20200605_105521](https://user-images.githubusercontent.com/1010226/83857349-25e5e380-a71b-11ea-88b9-279ee8b3a3bf.png)

I'm glad you made the script btw, but could you add some kind of instructions for people who just want to use Steam/proton (to know what wine prefix we're using, because I personally can't figure it out)

**Comment by shpinog** [comment]
> I'm not sure what it is you're asking.

I play DRG, there is integration with Discord. In the group (disagreement), people are inviting me to the game, but I don’t have the ability to join. Is it due to the rich presence or is this version of the Linux version of the discord?

**Comment by 0e4ef622** [comment]
_Joining_ a game from Discord doesn't use Rich Presence, so this program won't help with that, that's more to do with getting your system to associate a certain URL with the game.

**Comment by hagabaka** [comment]
> I'm glad you made the script btw, but could you add some kind of instructions for people who just want to use Steam/proton (to know what wine prefix we're using, because I personally can't figure it out)
If you use Steam launch options to run the script, Steam will set environment variables so that the bridge is launched using the correct `wine` and `WINEPREFIX`.

**Comment by thibaultmol** [comment]
@hagabaka so what's the exact line that I need to put into the launch options?

**Comment by hagabaka** [comment]
> @hagabaka so what's the exact line that I need to put into the launch options?

`/path/to/winediscordipcbridge-steam.sh %command%`, or if you save the script in `PATH`, just `winediscordipcbridge-steam.sh %command%`. Also, edit the script so it has the correct path to `winediscordipcbridge.exe`.
